object PrjDependencies {
    //Library packages (alphabetic order)
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val cardView = "androidx.cardview:cardview:${Versions.supportLib}"
    const val coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:${Versions.coordinatorLayout}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerAndroid = "com.google.dagger:dagger-android:${Versions.dagger}"
    const val daggerAndroidSupport = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideOkHttp = "com.github.bumptech.glide:okhttp3-integration:${Versions.glide}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val legacySupport = "androidx.legacy:legacy-support-v4:${Versions.supportLib}"
    const val lifecycleCommon = "androidx.lifecycle:lifecycle-common:${Versions.lifecycle}"
    const val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val lifecycleStreams = "androidx.lifecycle:lifecycle-reactivestreams:${Versions.lifecycle}"
    const val materialDesign = "com.google.android.material:material:${Versions.supportLib}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val okHttpInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    const val paging = "paging:paging-runtime:${Versions.paging}"
    const val pagingRx = "androidx.paging:paging-rxjava2:${Versions.paging}"
    const val pagingKtx = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${Versions.supportLib}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val retrofitRxJava = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val room = "androidx.room:room-runtime:${Versions.room}"
    const val roomRxJava = "androidx.room:room-rxjava2:${Versions.room}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    const val rxRelay = "com.jakewharton.rxrelay2:rxrelay:${Versions.rxRelay}"
    const val transition = "androidx.transition:transition:${Versions.transition}"
}

object AnnotationProcessors {
    const val archLifecycle = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"
    const val dagger = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val daggerAndroid = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val glide = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"
    const val room = "androidx.room:room-compiler:${Versions.room}"
}

object TestDependencies {
    const val androidTestRules = "androidx.test:rules:${Versions.androidTest}"
    const val androidTestRunner = "androidx.test:runner:${Versions.androidTest}"
    const val archCoreTest = "androidx.arch.core:core-testing:${Versions.archCoreTestVersion}"
    const val assertJ = "org.assertj:assertj-core:${Versions.assertJ}"
    const val jUnit = "junit:junit:${Versions.jUnit}"
    const val mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockitoKotlin}"
    const val okHttpMock = "com.squareup.okhttp3:mockwebserver:${Versions.okHttp}"
}